version: '3.8'

services:
  mnist-server:
    container_name: mnist-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./src2:/home/ubuntu
    ports:
      - 8000:8000
    entrypoint: /bin/bash
    stdin_open: true
    tty: true