version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/home/ubuntu
    ports:
      - 8000:8000
    entrypoint: /bin/bash
    stdin_open: true
    tty: true